### ISSUE TITLE
Issues with role on Ubuntu 20.04

### ISSUE THREAD

**Issue by zinefer** [heytrav/ansible-influxdb#1]
Thanks for your work on this project!

On Ubuntu 20.04 I am erroring on the `python-pip` install. Changing it to `python3-pip` seems to [fix it](https://github.com/zinefer/ansible-influxdb/commit/7afcae2dba725f0660d81f4cd78b6c0f5152739d) for me.

**Comment by heytrav** [comment]
I just realised that I had it set to install `python3-pip` on the the branch, but hadn't pushed a tag for that yet. If you try version 1.0.1 does that work for you?

**Comment by zinefer** [comment]
This seems to be working for me now, thank you!
